name: Build
on:
  - workflow_dispatch
jobs:
  build_package:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        architecture:
          - armhf
          - arm64
        include:
          - architecture: armhf
            docker_platform: linux/arm/v7
          - architecture: arm64
            docker_platform: linux/arm64
    container:
      image: debian:trixie
      options: --platform ${{ matrix.docker_platform }}
    steps:
      - name: Show dpkg native architecture
        run: dpkg --print-architecture
